#!/usr/bin/env python3
"""
setup_run.py — Prepare and submit an IBAMR rotating cylinder simulation run.

Run this from anywhere:
    python3 setup_run.py

Creates a timestamped folder under runs/ with this structure:
    runs/YYYY-MM-DD_HH-MM-SS/
        archive/              ← snapshot of all source files
        viz_cylinder3d/       ← simulation visualization output (pre-created)
        restart_IB3d/         ← simulation restart checkpoints (pre-created)
        cylinder_dump/        ← constraint IB force/velocity output (pre-created)
        Dump--Cylinder/       ← constraint IB dump output (pre-created)
        cylinder3d.vertex     ← generated by Cylinder.py
        indices               ← generated by Cylinder.py
        input3d               ← copy of simulation input file
"""

import os
import sys
import shutil
import subprocess
from datetime import datetime
from pathlib import Path

# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------
PROJECT_DIR = Path(__file__).resolve().parent
RUNS_DIR    = PROJECT_DIR

# Source files to snapshot in archive/
SOURCE_FILES = [
    "example.C",
    "CartGridBodyForce.C",
    "CartGridBodyForce.h",
    "ForceProjector.C",
    "ForceProjector.h",
    "OscillatingCylinderKinematics.h",
    "RotatingCylinderKinematics.C",
    "RotatingCylinderKinematics.h",
    "CMakeLists.txt",
    "Makefile",
    "Cylinder.py",
    "input3d",
    "singularity/ibamr.def",
    "singularity/build-container.sh",
    "singularity/run-IBAMR-torch.bash",
    "singularity/run-simulation.slurm",
    "setup_run.py",
]

# Empty output directories the simulation expects to find or will create
SIM_OUTPUT_DIRS = [
    "viz_cylinder3d",
    "restart_IB3d",
    "cylinder_dump",
    "Dump--Cylinder",
]

# -------------------------------------------------------------------------

def main():
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    run_dir   = RUNS_DIR / timestamp

    print(f"=== Setting up run: {timestamp} ===")
    print(f"  Run directory: {run_dir}\n")

    # ------------------------------------------------------------------
    # 1. Create directory structure
    # ------------------------------------------------------------------
    run_dir.mkdir(parents=True)
    archive_dir = run_dir / "archive"
    archive_dir.mkdir()
    for d in SIM_OUTPUT_DIRS:
        (run_dir / d).mkdir()
    print(f"  [1/4] Created run directory structure")

    # ------------------------------------------------------------------
    # 2. Archive source files
    # ------------------------------------------------------------------
    missing = []
    for rel in SOURCE_FILES:
        src = PROJECT_DIR / rel
        if src.exists():
            shutil.copy2(src, archive_dir / src.name)
        else:
            missing.append(rel)
    if missing:
        print(f"        WARNING: missing source files (not archived): {missing}")
    print(f"  [2/4] Archived {len(SOURCE_FILES) - len(missing)} source files → archive/")

    # ------------------------------------------------------------------
    # 3. Run Cylinder.py to generate vertex + indices files
    #    Run with cwd=run_dir so output files land there directly.
    #    MPLBACKEND=Agg prevents plt.show() from blocking on headless nodes.
    # ------------------------------------------------------------------
    print(f"  [3/4] Running Cylinder.py ...")
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"

    # Use the anaconda3 python which has numpy/matplotlib
    anaconda_python = "/share/apps/anaconda3/2025.06/bin/python3"
    python_exe = anaconda_python if Path(anaconda_python).exists() else sys.executable

    result = subprocess.run(
        [python_exe, str(PROJECT_DIR / "Cylinder.py")],
        cwd=str(run_dir),
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("  ERROR: Cylinder.py failed:\n")
        print(result.stderr)
        sys.exit(1)

    # Print Cylinder.py output indented
    for line in result.stdout.strip().splitlines():
        print(f"        {line}")
    print(f"        → cylinder3d.vertex, indices written to run dir")

    # Copy input file into run directory
    shutil.copy2(PROJECT_DIR / "input3d", run_dir / "input3d")

    # ------------------------------------------------------------------
    # 4. Submit SLURM job
    # ------------------------------------------------------------------
    slurm_script = PROJECT_DIR / "singularity" / "run-simulation.slurm"
    executable   = PROJECT_DIR / "build" / "main3d"
    sif          = PROJECT_DIR / "singularity" / "ibamr.sif"

    print(f"\n  [4/4] Submitting SLURM job ...")

    for label, path in [("executable", executable), ("container", sif), ("slurm script", slurm_script)]:
        if not path.exists():
            print(f"  ERROR: {label} not found: {path}")
            if label == "executable":
                print("         Build first: bash singularity/run-IBAMR-torch.bash make-sim")
            sys.exit(1)

    result = subprocess.run(
        [
            "sbatch",
            f"--chdir={run_dir}",   # simulation runs from run_dir → outputs land there
            f"--export=ALL,IBAMR_PROJECT_DIR={PROJECT_DIR},IBAMR_SIF={sif},IBAMR_EXECUTABLE={executable}",
            str(slurm_script),
            "input3d",
        ],
        cwd=str(run_dir),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("  ERROR: sbatch failed:\n")
        print(result.stderr)
        sys.exit(1)

    job_info = result.stdout.strip()
    job_id   = job_info.split()[-1] if job_info else "?"

    print(f"        {job_info}")
    print(f"""
=== Run submitted ===
  Run folder : {run_dir}
  Job ID     : {job_id}

  Monitor    : squeue -u $USER
  Output log : {run_dir}/ibamr-rotating-cylinder-{job_id}.out
  Cancel     : scancel {job_id}
""")


if __name__ == "__main__":
    main()
